name 'local'
maintainer 'Steven Murawski'
maintainer_email 'smurawski@chef.io'
license 'apache2'
description 'Installs/Configures a local workstation'
long_description 'Installs/Configures a local workstation'
version '0.2.0'
